apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-chat
  template:
    metadata:
      labels:
        app: health-chat
    spec:
      containers:
        - name: health-chat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /app/public/config.js
              subPath: config.js
              readOnly: true
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: health-chat-config
