apiVersion: v1
kind: Service
metadata:
  name: health-chat
spec:
  selector:
    app: health-chat
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
