apiVersion: v1
kind: Service
metadata:
  name: vehicle-manual-bot
spec:
  selector:
    app: vehicle-manual-bot
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
