image:
  # repository: ghcr.io/<GITHUB_OWNER>/api-fastapi
  # tag: "dev"
  repository: ghcr.io/leodev901/health-chat/backend
  tag: "latest"
  pullPolicy: Always

service:
  port: 80
  targetPort: 8080

env:
  APP_NAME: "Health Chat API"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8080"
  APP_LOG_LEVEL: "debug"
  PROVIDER: "OPENAI"
  OPENAI_API_KEY: "replace-openai-api-key"
  OPENAI_MODEL: "gpt-4o-mini"
  GEMINI_API_KEY: "replace-gemini-api-key"
  GEMINI_MODEL: "gemini-2.5-flash"
  GEMINI_BASE_URL: ""

