apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-chat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-chat-api
  template:
    metadata:
      labels:
        app: health-chat-api
    spec:
      containers:
        - name: health-chat-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 360
