apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SUPABASE_URL: "{{ .Values.env.supabase_url }}"
  SUPABASE_KEY: "{{ .Values.env.supabase_key }}"
  DATABASE_URL: "{{ .Values.env.database_url }}"
  OPENAI_API_KEY: "{{ .Values.env.openai_api_key }}"
  GEMINI_API_KEY: "{{ .Values.env.gemini_api_key }}"
  HF_TOKEN: "{{ .Values.env.hf_token }}"
