apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  SUPABASE_URL: {{ .Values.env.supabase.url | quote }}
  SUPABASE_KEY: {{ .Values.env.supabase.key | quote }}
  DATABASE_URL: {{ .Values.env.database.url | quote }}
  OPENAI_API_KEY: {{ .Values.env.llm.openai.api_key | quote }}
  GEMINI_API_KEY: {{ .Values.env.llm.gemini.api_key | quote }}
  XAI_API_KEY: {{ .Values.env.llm.xai.api_key | quote }}
  HF_TOKEN: {{ .Values.env.huggingface.token | quote }}
